services:
  summaly:
    image: ghcr.io/yamisskey/summaly-docker:latest
    container_name: 'summaly'
    hostname: 'summaly'
    restart: always

  proxy:
    image: nginx
    container_name: 'proxy'
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/default.conf:ro
